import type { DatabaseShape } from "@/types/domain";
import { addDaysISO, todayISO } from "@/utils/dates";
import { createId } from "@/utils/ids";

export function createSeedDatabase(): DatabaseShape {
  const clientA = createId("client");
  const clientB = createId("client");
  const equipmentA = createId("equipment");
  const equipmentB = createId("equipment");
  const rentalA = createId("rental");
  const rentalB = createId("rental");
  const now = new Date().toISOString();

  return {
    clients: [
      {
        id: clientA,
        name: "Mariana Souza",
        document: "123.456.789-10",
        phone: "(65) 99910-2001",
        whatsapp: "(65) 99910-2001",
        email: "mariana@exemplo.com",
        address: "Av. Brasil, 1200",
        city: "Cuiaba",
        state: "MT",
        notes: "Cliente recorrente para eventos corporativos.",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: clientB,
        name: "Studio Prime Eventos",
        document: "12.345.678/0001-90",
        phone: "(65) 3322-4500",
        whatsapp: "(65) 99220-4500",
        email: "contato@studioprime.com",
        address: "Rua das Flores, 85",
        city: "Varzea Grande",
        state: "MT",
        notes: "Solicita montagem tecnica completa.",
        createdAt: now,
        updatedAt: now,
      },
    ],
    equipment: [
      {
        id: equipmentA,
        category: "Som",
        name: "Caixa ativa 1000W",
        brand: "JBL",
        model: "PRX One",
        patrimony: "PAT-0012",
        internalCode: "SOM-CAIXA-001",
        quantity: 8,
        dailyRate: 180,
        weekendRate: 420,
        weeklyRate: 980,
        status: "Disponivel",
        photos: [],
        notes: "Kit com pedestal e cabo de energia.",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: equipmentB,
        category: "Iluminacao",
        name: "Moving Beam 230",
        brand: "Nagy Tech",
        model: "Beam Pro",
        patrimony: "PAT-0048",
        internalCode: "LUZ-MOV-230",
        quantity: 12,
        dailyRate: 160,
        weekendRate: 390,
        weeklyRate: 900,
        status: "Reservado",
        photos: [],
        notes: "Revisar lampadas a cada 12 eventos.",
        createdAt: now,
        updatedAt: now,
      },
    ],
    rentals: [
      {
        id: rentalA,
        clientId: clientA,
        clientName: "Mariana Souza",
        items: [
          {
            equipmentId: equipmentA,
            equipmentName: "Caixa ativa 1000W",
            quantity: 2,
            unitValue: 180,
          },
        ],
        pickupDate: todayISO(),
        pickupTime: "14:00",
        returnDate: addDaysISO(2),
        returnTime: "10:00",
        value: 680,
        discount: 40,
        freight: 80,
        assembly: 120,
        status: "Separacao",
        notes: "Evento em buffet fechado.",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: rentalB,
        clientId: clientB,
        clientName: "Studio Prime Eventos",
        items: [
          {
            equipmentId: equipmentB,
            equipmentName: "Moving Beam 230",
            quantity: 6,
            unitValue: 160,
          },
        ],
        pickupDate: addDaysISO(1),
        pickupTime: "09:00",
        returnDate: addDaysISO(4),
        returnTime: "18:00",
        value: 1450,
        discount: 0,
        freight: 150,
        assembly: 340,
        status: "Agendado",
        notes: "Separar case e mesa DMX.",
        createdAt: now,
        updatedAt: now,
      },
    ],
    expenses: [
      {
        id: createId("expense"),
        category: "Manutencao",
        supplier: "Eletrica Centro",
        description: "Reposicao de cabos e conectores",
        value: 420,
        paymentMethod: "Pix",
        dueDate: addDaysISO(1),
        paymentDate: "",
        status: "Pendente",
        attachments: [],
        notes: "Pagar apos retirada dos materiais.",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: createId("expense"),
        category: "Transporte",
        supplier: "Frota Parceira",
        description: "Frete evento corporativo",
        value: 750,
        paymentMethod: "Boleto",
        dueDate: todayISO(),
        paymentDate: "",
        status: "Vencido",
        attachments: [],
        notes: "Conferir comprovante.",
        createdAt: now,
        updatedAt: now,
      },
    ],
    users: [
      {
        id: createId("user"),
        name: "Administrador NAGY",
        email: "admin@nagyeventos.com.br",
        role: "Administrador",
        avatarUrl: "",
        lastAccess: now,
        status: "active",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: createId("user"),
        name: "Operacao",
        email: "operacao@nagyeventos.com.br",
        role: "Operacional",
        avatarUrl: "",
        lastAccess: now,
        status: "active",
        createdAt: now,
        updatedAt: now,
      },
    ],
    notifications: [],
    auditLogs: [
      {
        id: createId("audit"),
        action: "login",
        module: "Sistema",
        userName: "Administrador NAGY",
        description: "Ambiente demo inicializado.",
        createdAt: now,
        updatedAt: now,
      },
    ],
  };
}
